### PR TITLE
Retail - added documentation for Intelligent Recommendation deployment

### LINKED ISSUE #256: Retail - Complete documentation and guidance for Intelligent Recommendations
Work in progress.

### PR DESCRIPTION
**Pull request by amanjeetsingh**
## PR Checklist
* [x] Closes Issue #xxx
* [x] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by amanjeetsingh** [comment]
This PR is in Draft state. Please do not change state. Thanks!

**Comment by amanjeetsingh** [comment]
I'll address linting errors at the end before this PR is ready. Thanks!

**Comment by amanjeetsingh** [comment]
Added more details in relation to security and networking aspects of IR. Will fix up linting issues once draft is complete. Aiming for Sunday 03-04-2022

**Review by sasever — DISMISSED** [review]
LGTM

**Comment by amanjeetsingh** [comment]
@sasever  - this is ready for review. Thanks!

**Review by rocavalc — APPROVED** [review]
LGTM

**Pull request merged**
