### PR TITLE
industry reference implementations

### LINKED ISSUE #353: FSI Landing Zones on Microsoft Azure documentation
Provide documentation for FSI Landing Zones on Microsoft Azure

* Architecture and design
* Reference implementation
* Service Enablement Framework 2.0 for FSI
* Operational Excellence
* Security, governance, and compliance by-default
* Enablement and acceleration of compliant workloads

### PR DESCRIPTION
**Pull request by krnese**
## PR Checklist
* [ ] Closes Issue #xxx
* [ ] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by sasever** [comment]
@krnese I see that initial readme  containing MC4F info is renamed and not referenced anywhere, there is an update for that diagram  and that info should be referenced since it also references other MC4F components.

**Comment by krnese** [comment]
> @krnese I see that initial readme containing MC4F info is renamed and not referenced anywhere, there is an update for that diagram and that info should be referenced since it also references other MC4F components.

Yes, we will find the right place for it. I am targeting the Azure-only parts with this PR and the current readme spans more than just that :-)

**Comment by sasever** [comment]
> > @krnese I see that initial readme containing MC4F info is renamed and not referenced anywhere, there is an update for that diagram and that info should be referenced since it also references other MC4F components.
> 
> Yes, we will find the right place for it. I am targeting the Azure-only parts with this PR and the current readme spans more than just that :-)

Waiting for your changes to add the new diagram and visio then.

**Review by daltondhcp — APPROVED** [review]
💣

**Pull request merged**
