### PR TITLE
Added files for flexible fulfillment and TFW

### PR DESCRIPTION
**Pull request by amanjeetsingh**
## PR Checklist
* [x] Closes Issue #xxx
* [x] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by amanjeetsingh** [comment]
Under review. Please do not merge.

**Comment by amanjeetsingh** [comment]
Team will be reviewing this PR on Friday 10th June 2022.
Linting errors are related to usage of the word "websites". We need to use this verbiage as this is what's used across Clarity's public-facing documentation and in the app itself.

**Review by rocavalc — APPROVED** [review]
LGTM

**Comment by amanjeetsingh** [comment]
Addresses issue https://github.com/microsoft/industry/issues/266

**Pull request merged**
