### PR TITLE
Added content for retail

### PR DESCRIPTION
**Pull request by amanjeetsingh**
## PR Checklist
* [ ] Closes Issue #xxx
* [ ] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by amanjeetsingh** [comment]
1. Adjusted structure of retail guidance
2. Adjusted structure/scope of retail solutions
3. Adjusted structure/scope of retail reference implementation

**Review by andrehass — DISMISSED** [review]
LGTM

**Review by sasever — APPROVED** [review]
Good to Go

**Review by andrehass — COMMENTED** [review]
LGTM

**Pull request merged**
