### PR TITLE
Added content for retail

### PR DESCRIPTION
**Pull request by amanjeetsingh**
## Summary of the Pull Request

This PR contains documentation only. No automation code or templates are included.
Changes include:
1. Documentation for retail
2. Updated formatting for retail to be in line with other industry cloud guidances

## PR Checklist
* [ ] Closes Issue #xxx
* [ ] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by amanjeetsingh** [comment]
@andrehass

**Review by rocavalc — COMMENTED** [review]
LGTM

**Review by rocavalc — APPROVED** [review]
approving changes

**Comment by rocavalc** [comment]
Merging repo with updates from amangeetsingh

**Pull request merged**
